endpoints:
    enabled: false
logging:
    level:
        edu.umich.api.tester: DEBUG
        org.springframework.web: DEBUG
        org.hibernate: ERROR
    file: api-tester.log
management:
    security:
        role: SUPERUSER
    port: 8081
security:
    user:
        name: admin
        password: secret
server:
    port: 8080
somekey:
    frequency: 1
spring:
    datasource:
        mongodb:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost/test
            username: dbuser
            password: dbpass
