logging:
    level:
        edu.umich.api.tester: INFO
        org.springframework.web: INFO
        org.hibernate: INFO
    file: api-tester.log
server:
    port: 8080
frequency: 1
#spring:
#    datasource:
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost/test
#        username: dbuser
#        password: dbpass
